name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: openjdk:17-jdk
      options: --user root

    steps:
    - uses: actions/checkout@v2.2.0
    - run: |
          chmod +x ./gradlew
          ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: fabric-build-artifacts
        path: fabric/build/libs/
    - uses: actions/upload-artifact@v2
      with:
        name: forge-build-artifacts
        path: forge/build/libs/